### ISSUE TITLE
Modal do not close on success event

### ISSUE THREAD

**Issue by yhortuk** [kompo/kompo#2]
Form.vue  emits this.$emit('success',response, submitKomponent), but it never reach EditLinkModalContent.vue so modal  window never closes itself. I tired to add sample button with click event to Form.vue and it works correctly. 
Can't locate the source of a problem myself. I hope you can hint me on what I'm doing wrong here.

RegularForm.php
```
class RegularForm extends Form
{
	public function handle()
	{
		return true;
	}

	public function komponents()
	{
		return [
                     _EditButton('Modal Form')->getKomposer(ModalForm::class)->inModal(),
                ];
        }
}
```

ModalForm.php
```
class ModalForm extends Form
{
    public function handle()
    {
        return true;
    }

    public function komponents()
    {
        return [
            _SubmitButton("Test")
        ];
    }
}
```

**Comment by kompo** [comment]
Hi, I am not sure I fully understand your issue, but I already see something not right in `RegularForm.php`'s code. 

_EditButton (like _EditLink, _AddLink, etc...) have a built-in modal interaction. I should probably rename them EditButtonInModal to make this fact clearer. So you shouldn't chain `->inModal()` because it overrides their default behavior.  

This is enough:
`_EditButton('Modal Form')->getKomposer(ModalForm::class)`

By using it like this (default behavior), this allows EditLinkModalContent to load in the Komposer's SupportModal which will close and even conveniently refresh the items in a Query when used in that context.

Let me know if this answers the question, otherwise send me more info.

**Comment by yhortuk** [comment]
@kompo Thanks a lot! It was the cause for me. Without ->inModal call everything is handled properly.
