### ISSUE TITLE
💡 Could you opensource Kompo.io?

### ISSUE THREAD

**Issue by jechaviz** [kompo/kompo#22]
The documentation online is good, but you did things that look like it needs to review models, route calls, and other things. If we can see what you do in Kompo.io many questions I have could be answered just by seeing the code.

Thank you so much again.

**Comment by kompo** [comment]
Yes I understand, I had many developers asking for more examples because Kompo does a lot of magic and it's not always easy to understand what's happening. This is why I am working on a new section of the site that will display a whole library of examples + demo that you could pull directly into your code. I'm hoping to release it at the end of october! Thanks for your patience

**Comment by jechaviz** [comment]
Thank you for your answer, and I would like to praise your work again as genius work (best in class and far superior to filament admin and others), just, pardon me if I insist. I really appreciate what you are doing and planning to release next October, but you already have the code, and you don't need to work on it, of what you have already published in kompo.io, and is directly related with the already official documentation, Why I insist? To avoid usage questions, because we are already using this magical framework to make magic. Thank you, and congratulations again.

**Comment by kompo** [comment]
I am sorry but I cannot open source the website. First, it has been coded more than a year ago and Kompo has evolved a lot since. Second, it is not even that interesting from an educational perspective because it's mostly static documentation/api pages and there are no ajax heavy interactions... 

Since that time, I have been able to make a Kanban app, a Forum, messaging/inbox, reservation/calendar modules, and much more with Kompo and I will showcase them all in October.

In the meantime, I suggest the following: please tell me ALL the areas you would like me to explain better right now and/or need more practical examples on, and I will do it this week. 

Thanks for your patience :)
